export default [
  {
    id: '2686837a-6873-4f6a-8759-0ffe024bb076',
    user: {
      firstname: 'Sheelah',
      lastname: 'Doyley',
      avatar_url: 'https://robohash.org/natusquiadipisci.png?size=50x50&set=set1',
      job: 'Senior Quality Engineer',
      following: 16,
    },
    created_at: '10/23/2022',
    description: 'Assault by sharp glass, initial encounter',
    total_visits: 85,
    total_comments: 54,
    viewed_by: [
      {
        firstname: 'Emalee',
        lastname: 'Rawlyns',
        avatar_url: 'https://robohash.org/doloribusestdolore.png?size=50x50&set=set1',
        job: 'Unsp injury of anterior tibial artery, right leg, sequela',
        following: 43,
        id: 'f6e0be18-e627-43bc-b9fb-51f24875640e',
      },
      {
        firstname: 'Teodorico',
        lastname: 'McCluney',
        avatar_url: 'https://robohash.org/nisiquasitempora.png?size=50x50&set=set1',
        job: 'Legal intervnt w unsp explosv, law enforc offl injured, init',
        following: 69,
        id: 'cd2e8751-f3c9-4752-a5d9-df6dd6f83cc6',
      },
      {
        firstname: 'Alix',
        lastname: 'Lucchi',
        avatar_url: 'https://robohash.org/etodiodebitis.png?size=50x50&set=set1',
        job: 'Malignant neoplasm of undescended right testis',
        following: 90,
        id: 'd3c4cd47-794b-44de-9098-a1e641bb7401',
      },
      {
        firstname: 'Klaus',
        lastname: 'Blanche',
        avatar_url: 'https://robohash.org/velitaquesunt.png?size=50x50&set=set1',
        job: 'Other contact with shark',
        following: 46,
        id: 'd01657bd-b59e-4469-95f2-c4db91b9d167',
      },
      {
        firstname: 'Caz',
        lastname: 'Shimwell',
        avatar_url: 'https://robohash.org/temporesequiconsequatur.png?size=50x50&set=set1',
        job: 'Oth fracture of T9-T10 vertebra, subs for fx w routn heal',
        following: 63,
        id: '77b3daeb-7a06-4e30-b7ba-95defba43618',
      },
    ],
  },
  {
    id: '79692b95-0585-4dc4-9ee7-2080513755d9',
    user: {
      firstname: 'Rudy',
      lastname: 'Burgisi',
      avatar_url: 'https://robohash.org/magnamdelenitireiciendis.png?size=50x50&set=set1',
      job: 'Sales Associate',
      following: 99,
    },
    created_at: '3/13/2022',
    description: 'Other disorders of muscle tone of newborn',
    total_visits: 43,
    total_comments: 97,
    viewed_by: [
      {
        firstname: 'Alison',
        lastname: 'Wabe',
        avatar_url: 'https://robohash.org/adquomagni.png?size=50x50&set=set1',
        job: 'Exposure to other ionizing radiation',
        following: 65,
        id: 'e2c980c1-717c-44c5-8875-02ba58f3ecb9',
      },
      {
        firstname: 'Emelina',
        lastname: 'Jerosch',
        avatar_url: 'https://robohash.org/quidemasperioresnihil.png?size=50x50&set=set1',
        job: 'Terrorism involving nuclear weapons, terrorist injured, init',
        following: 17,
        id: 'f4f6a4ff-a238-454b-b39a-8991b34f1130',
      },
      {
        firstname: 'Theobald',
        lastname: 'Kirtland',
        avatar_url: 'https://robohash.org/facilisofficiain.png?size=50x50&set=set1',
        job: 'Other intervertebral disc displacement, thoracic region',
        following: 51,
        id: '2fe8a8e2-6dd9-4d09-9f9b-07e1cc011f98',
      },
    ],
  },
  {
    id: 'a8622398-fe30-4330-9542-1750994dddbb',
    user: {
      firstname: 'Clevie',
      lastname: 'Tytterton',
      avatar_url: 'https://robohash.org/distinctioconsequaturmodi.png?size=50x50&set=set1',
      job: 'Database Administrator I',
      following: 87,
    },
    created_at: '10/11/2022',
    description: 'Fall from non-moving wheelchair, initial encounter',
    total_visits: 8,
    total_comments: 56,
    viewed_by: [
      {
        firstname: 'Artie',
        lastname: 'Flannery',
        avatar_url: 'https://robohash.org/accusamusoptioodio.png?size=50x50&set=set1',
        job: 'Strain of extensor musc/fasc/tend l rng fngr at forarm lv',
        following: 4,
        id: 'e20f808d-d4cc-40e6-aa0d-f6008857ea28',
      },
      {
        firstname: 'Chloe',
        lastname: 'Lacknor',
        avatar_url: 'https://robohash.org/iurenumquamdistinctio.png?size=50x50&set=set1',
        job: 'Nondisp unsp fx unsp great toe, subs for fx w delay heal',
        following: 7,
        id: '9b765b9b-48c8-41a6-826c-74e573346564',
      },
      {
        firstname: 'Sibylle',
        lastname: 'Laurentin',
        avatar_url: 'https://robohash.org/quiquisomnis.png?size=50x50&set=set1',
        job: 'Labor and delivery complicated by prolapse of cord',
        following: 79,
        id: '68f89d47-7b53-4ef3-8041-48598a8755ac',
      },
      {
        firstname: 'Dorry',
        lastname: 'Jopke',
        avatar_url: 'https://robohash.org/officiisaomnis.png?size=50x50&set=set1',
        job: 'Acquired absence of leg above knee',
        following: 58,
        id: '11d2ac68-f235-4692-9548-cf2b58b2daab',
      },
    ],
  },
  {
    id: 'f288def3-520b-4e1c-a416-44f2aee91be3',
    user: {
      firstname: 'Lawry',
      lastname: 'Tune',
      avatar_url: 'https://robohash.org/velitmagnipraesentium.png?size=50x50&set=set1',
      job: 'Budget/Accounting Analyst II',
      following: 41,
    },
    created_at: '4/15/2022',
    description: 'Encounter for fitting and adjustment of other devices',
    total_visits: 29,
    total_comments: 10,
    viewed_by: [
      {
        firstname: 'Eloisa',
        lastname: 'Denmead',
        avatar_url: 'https://robohash.org/beataevoluptasest.png?size=50x50&set=set1',
        job: 'Unsp open wound of right great toe w damage to nail, subs',
        following: 49,
        id: 'b90c0148-77f0-46aa-aee0-061363424bcc',
      },
      {
        firstname: 'Elsy',
        lastname: 'Mibourne',
        avatar_url: 'https://robohash.org/eosrerumvoluptatem.png?size=50x50&set=set1',
        job: 'Pathological fracture, left radius, sequela',
        following: 10,
        id: 'b58f289e-6a80-4980-8c19-3b21681866a3',
      },
    ],
  },
  {
    id: 'bba1a05c-7685-482e-93bc-77855cddd42e',
    user: {
      firstname: 'Chaunce',
      lastname: 'Cypler',
      avatar_url: 'https://robohash.org/delenitiatquesapiente.png?size=50x50&set=set1',
      job: 'Financial Advisor',
      following: 19,
    },
    created_at: '11/21/2022',
    description: 'Exposure to radon, sequela',
    total_visits: 17,
    total_comments: 99,
    viewed_by: [
      {
        firstname: 'Ardys',
        lastname: 'Ellwand',
        avatar_url: 'https://robohash.org/nobisnecessitatibusfugit.png?size=50x50&set=set1',
        job: 'Quad pregnancy, unable to determine num plcnta & amnio sacs',
        following: 32,
        id: 'c9129df7-6163-410e-a32a-3cf841a94c4f',
      },
      {
        firstname: 'Florenza',
        lastname: 'Phipps',
        avatar_url: 'https://robohash.org/perspiciatisetnihil.png?size=50x50&set=set1',
        job: 'Immersion hand, left hand',
        following: 64,
        id: '4e82b3c0-8b42-41c9-9dff-ef14b32e375e',
      },
      {
        firstname: 'Rachel',
        lastname: 'Olivello',
        avatar_url: 'https://robohash.org/nihilconsecteturmaxime.png?size=50x50&set=set1',
        job: 'Major laceration of unspecified vertebral artery, sequela',
        following: 12,
        id: '3be57956-8aa1-48d8-977f-23ccc8b54aff',
      },
      {
        firstname: 'Lulu',
        lastname: 'Vallens',
        avatar_url: 'https://robohash.org/tenetursedducimus.png?size=50x50&set=set1',
        job: 'Embolism due to vascular prosth dev/grft, initial encounter',
        following: 54,
        id: '32db1947-0f03-4bb7-85ab-f66c6d260aef',
      },
      {
        firstname: 'Ashton',
        lastname: 'Brose',
        avatar_url: 'https://robohash.org/doloremquedebitisfacilis.png?size=50x50&set=set1',
        job: 'Disp fx of 4th metatarsal bone, l ft, subs for fx w malunion',
        following: 84,
        id: '2ba9d6fc-8f5a-419e-a7db-dbe32855aab7',
      },
    ],
  },
  {
    id: 'a407ca91-68d5-4a98-999a-b388010bc2bc',
    user: {
      firstname: 'Leroi',
      lastname: 'Rennard',
      avatar_url: 'https://robohash.org/harumautemlibero.png?size=50x50&set=set1',
      job: 'Chemical Engineer',
      following: 93,
    },
    created_at: '2/4/2022',
    description: 'Crushing injury of unspecified foot, initial encounter',
    total_visits: 93,
    total_comments: 76,
    viewed_by: [
      {
        firstname: 'Lora',
        lastname: 'Doick',
        avatar_url: 'https://robohash.org/quisquiasit.png?size=50x50&set=set1',
        job: 'Pnctr w fb of r little finger w/o damage to nail, init',
        following: 10,
        id: '589cf8b5-e5a0-4e25-bda7-738e5b2b6645',
      },
      {
        firstname: 'Elsa',
        lastname: 'Philipsohn',
        avatar_url: 'https://robohash.org/doloremautminus.png?size=50x50&set=set1',
        job: 'Fall into swimming pool strk surfc causing oth injury, init',
        following: 51,
        id: 'de6f3665-722e-4bd0-953a-cbe6ca5265ae',
      },
    ],
  },
  {
    id: 'f3dcdb0f-64f1-48a8-a479-bb1b3dd597d8',
    user: {
      firstname: 'Skipper',
      lastname: 'Gudahy',
      avatar_url: 'https://robohash.org/culpadoloremquesint.png?size=50x50&set=set1',
      job: 'Business Systems Development Analyst',
      following: 93,
    },
    created_at: '1/14/2022',
    description: 'Wandering in diseases classified elsewhere',
    total_visits: 38,
    total_comments: 86,
    viewed_by: [
      {
        firstname: 'Minta',
        lastname: 'Feeley',
        avatar_url: 'https://robohash.org/velitullamrerum.png?size=50x50&set=set1',
        job: 'Type 1 diabetes with prolif diabetic rtnop with comb detach',
        following: 83,
        id: 'af78b809-7678-49b4-8d46-93370c6d33ae',
      },
      {
        firstname: 'Wendell',
        lastname: 'Jerzak',
        avatar_url: 'https://robohash.org/doloremconsequunturcorrupti.png?size=50x50&set=set1',
        job: 'Unsp soft tissue disord rel to use/pressure, right ank/ft',
        following: 46,
        id: '840091d5-7981-409a-a6f0-14bb6c028c7c',
      },
    ],
  },
  {
    id: '8cc702b6-3e05-4c79-905a-1d90f54d12f9',
    user: {
      firstname: 'Deerdre',
      lastname: 'Dockery',
      avatar_url: 'https://robohash.org/istequaeratfugiat.png?size=50x50&set=set1',
      job: 'Geological Engineer',
      following: 51,
    },
    created_at: '8/25/2022',
    description: 'Other specified disorders of tendon, right knee',
    total_visits: 19,
    total_comments: 30,
    viewed_by: [
      {
        firstname: 'Violet',
        lastname: 'Chaffin',
        avatar_url: 'https://robohash.org/eaoccaecatiet.png?size=50x50&set=set1',
        job: 'Lacerat flexor musc/fasc/tend l rng fngr at forarm lv, init',
        following: 38,
        id: '6d5caef7-190d-49c7-b58d-cae7ef843ab9',
      },
      {
        firstname: 'Cristina',
        lastname: 'Bichard',
        avatar_url: 'https://robohash.org/autemdoloresipsam.png?size=50x50&set=set1',
        job: 'Unsp GU tract infection in pregnancy, first trimester',
        following: 100,
        id: 'b52da159-66ae-4e12-93b7-0e34939bfc50',
      },
      {
        firstname: 'Griselda',
        lastname: 'Scatchard',
        avatar_url: 'https://robohash.org/temporequoslaboriosam.png?size=50x50&set=set1',
        job: 'Poisoning by unsp antidepressants, assault, init encntr',
        following: 38,
        id: '41a0a45d-c9b7-488b-ac50-f21f8caa48a2',
      },
      {
        firstname: 'Kathe',
        lastname: 'Palmer',
        avatar_url: 'https://robohash.org/etsimiliquecumque.png?size=50x50&set=set1',
        job: 'Kitchen in oth residential institution as place',
        following: 57,
        id: '9282e519-974b-4ed6-9338-1ef00707bf89',
      },
      {
        firstname: 'Aurea',
        lastname: 'Blenkin',
        avatar_url: 'https://robohash.org/voluptatemporrovoluptatibus.png?size=50x50&set=set1',
        job: 'Congenital absence of left foot and toe(s)',
        following: 4,
        id: '20aed2e3-1e95-433a-bf84-cbe795fe60e0',
      },
    ],
  },
  {
    id: 'ed6eca93-d4b1-442b-8b11-3bb19ebb7a98',
    user: {
      firstname: 'Augusto',
      lastname: 'Innes',
      avatar_url: 'https://robohash.org/utquosmagnam.png?size=50x50&set=set1',
      job: 'Internal Auditor',
      following: 66,
    },
    created_at: '8/28/2022',
    description: 'Other diseases of pulmonary vessels',
    total_visits: 48,
    total_comments: 79,
    viewed_by: [
      {
        firstname: 'Bern',
        lastname: 'Sizey',
        avatar_url: 'https://robohash.org/ducimusveroautem.png?size=50x50&set=set1',
        job: 'Unspecified fracture of right calcaneus',
        following: 3,
        id: '18ddaa31-2779-4257-80d9-9664b0cd77cf',
      },
      {
        firstname: 'Fletcher',
        lastname: 'Sharp',
        avatar_url: 'https://robohash.org/sintvelitquibusdam.png?size=50x50&set=set1',
        job: 'Toxic effect of carbon dioxide, accidental (unintentional)',
        following: 91,
        id: 'd82b9cd8-6abe-45c5-b5e7-e677c24d29de',
      },
    ],
  },
  {
    id: '9174a4a4-fcfc-41ff-83d2-dfdd3c1765ed',
    user: {
      firstname: 'Analiese',
      lastname: 'Corzor',
      avatar_url: 'https://robohash.org/ducimusautexplicabo.png?size=50x50&set=set1',
      job: 'Actuary',
      following: 53,
    },
    created_at: '5/23/2022',
    description: 'Fracture of unsp parts of lumbosacral spine and pelvis, init',
    total_visits: 19,
    total_comments: 80,
    viewed_by: [
      {
        firstname: 'Delmer',
        lastname: 'Maciocia',
        avatar_url: 'https://robohash.org/quoetnecessitatibus.png?size=50x50&set=set1',
        job: 'Congenital malformation of anterior segment of eye, unsp',
        following: 12,
        id: 'bc3b7975-128c-4aec-9de9-8dfbf8525485',
      },
      {
        firstname: 'Delbert',
        lastname: 'deKnevet',
        avatar_url: 'https://robohash.org/autinqui.png?size=50x50&set=set1',
        job: 'War op w dest arcrft due to clsn w oth aircraft, milt, init',
        following: 89,
        id: '9c899f01-95ea-4e59-86e1-73e28b23b522',
      },
      {
        firstname: 'Misti',
        lastname: 'Tagg',
        avatar_url: 'https://robohash.org/molestiaeillumperspiciatis.png?size=50x50&set=set1',
        job: 'Disp fx (avulsion) of medial epicondyle of left humerus',
        following: 97,
        id: 'e0717066-9eb9-436e-aa8a-f52fd8ede1c2',
      },
      {
        firstname: 'Rosa',
        lastname: 'Rampton',
        avatar_url: 'https://robohash.org/nemoveroblanditiis.png?size=50x50&set=set1',
        job: 'Poisoning by antiasthmatics, accidental (unintentional)',
        following: 89,
        id: '52c01f2f-d025-4fc1-8477-b8ce89392603',
      },
    ],
  },
  {
    id: 'c0f65f8f-fb83-4e63-8d3e-7cf0161d11b5',
    user: {
      firstname: 'Zia',
      lastname: 'Glavis',
      avatar_url: 'https://robohash.org/cupiditatedoloremnon.png?size=50x50&set=set1',
      job: 'Senior Editor',
      following: 25,
    },
    created_at: '8/8/2022',
    description: 'Unspecified Eustachian tube disorder, left ear',
    total_visits: 99,
    total_comments: 9,
    viewed_by: [
      {
        firstname: 'Johnathan',
        lastname: 'Batchelour',
        avatar_url: 'https://robohash.org/reiciendisfugacumque.png?size=50x50&set=set1',
        job: 'Complete transverse atyp femoral fracture, left leg, 7thG',
        following: 42,
        id: '1e63cd20-08c4-4aae-ac4a-f3eacd358bb5',
      },
      {
        firstname: 'Bone',
        lastname: 'Dumphry',
        avatar_url: 'https://robohash.org/providentlaborumfugit.png?size=50x50&set=set1',
        job: 'Oth non-ABO incompat react d/t tranfs of bld/bld prod, sqla',
        following: 15,
        id: '219524db-2b1c-424d-9b62-e6b5b7ae5653',
      },
      {
        firstname: 'Rowland',
        lastname: 'Deboo',
        avatar_url: 'https://robohash.org/estnequedolorum.png?size=50x50&set=set1',
        job: 'Torsion of left ovary and ovarian pedicle',
        following: 93,
        id: '35c93835-2d03-4eda-bd76-9ee42c7af597',
      },
      {
        firstname: 'Keriann',
        lastname: 'Lowres',
        avatar_url: 'https://robohash.org/voluptasnondeleniti.png?size=50x50&set=set1',
        job: 'Sprain of left rotator cuff capsule, initial encounter',
        following: 31,
        id: 'ea64a13b-66a7-489a-b3d1-8c482809486a',
      },
      {
        firstname: 'Lilia',
        lastname: 'McCard',
        avatar_url: 'https://robohash.org/atqueetminima.png?size=50x50&set=set1',
        job: 'Laceration of muscles and tendons at ank/ft level, left foot',
        following: 11,
        id: '5d1f3dd9-0adf-4520-8c03-4279ce34fc2c',
      },
    ],
  },
  {
    id: 'ace3d011-00de-46f0-8b51-1a2251622f2f',
    user: {
      firstname: 'Meris',
      lastname: 'Flaverty',
      avatar_url: 'https://robohash.org/temporeetasperiores.png?size=50x50&set=set1',
      job: 'Civil Engineer',
      following: 53,
    },
    created_at: '4/3/2022',
    description: 'Other sprain of right thumb',
    total_visits: 39,
    total_comments: 28,
    viewed_by: [
      {
        firstname: 'Chane',
        lastname: 'Gannicott',
        avatar_url: 'https://robohash.org/temporaexpeditavero.png?size=50x50&set=set1',
        job: 'Burn of first degree of left wrist, subsequent encounter',
        following: 87,
        id: '1711760a-1f17-401f-a3a7-f5ce536740db',
      },
      {
        firstname: 'Boniface',
        lastname: 'Mercik',
        avatar_url: 'https://robohash.org/istetemporibusnobis.png?size=50x50&set=set1',
        job: 'Burn third deg of shldr/up lmb, ex wrs/hnd, unsp site, subs',
        following: 1,
        id: 'fb0fcb7f-54f5-4e65-826e-44651e78d9fb',
      },
    ],
  },
  {
    id: '29bb348b-cfe5-4632-983c-ec78811da3c3',
    user: {
      firstname: 'Flor',
      lastname: 'Kingswell',
      avatar_url: 'https://robohash.org/architectomolestiaecum.png?size=50x50&set=set1',
      job: 'Nurse Practicioner',
      following: 22,
    },
    created_at: '6/11/2022',
    description: 'Epidermal cyst',
    total_visits: 29,
    total_comments: 87,
    viewed_by: [
      {
        firstname: 'Mandie',
        lastname: 'Andreassen',
        avatar_url: 'https://robohash.org/animinemomolestias.png?size=50x50&set=set1',
        job: 'Stenosis of other vascular prosth dev/grft, subs',
        following: 68,
        id: 'a707d8d9-c71d-4784-93d9-64723d0e1764',
      },
      {
        firstname: 'Stephan',
        lastname: 'Cumming',
        avatar_url: 'https://robohash.org/etvoluptasin.png?size=50x50&set=set1',
        job: 'Displ seg fx shaft of unsp fibula, 7thF',
        following: 67,
        id: '74f5a8f3-5901-4722-b3b6-3697802f1602',
      },
      {
        firstname: 'Lisa',
        lastname: 'Jenk',
        avatar_url: 'https://robohash.org/suntipsumsimilique.png?size=50x50&set=set1',
        job: 'Maternal care for anti-D antibodies, first tri, fetus 5',
        following: 36,
        id: '63a9ee9b-3f5f-49f2-aa9c-0e63f6d65e9a',
      },
    ],
  },
  {
    id: '76bd8edf-e4b7-4ebe-9ef2-85985cdc84ab',
    user: {
      firstname: 'Lynnette',
      lastname: 'Swateridge',
      avatar_url: 'https://robohash.org/illumeosest.png?size=50x50&set=set1',
      job: 'Associate Professor',
      following: 82,
    },
    created_at: '3/21/2022',
    description: 'Abnormal involuntary movements',
    total_visits: 83,
    total_comments: 87,
    viewed_by: [
      {
        firstname: 'Susanetta',
        lastname: 'Mildenhall',
        avatar_url: 'https://robohash.org/utsiteligendi.png?size=50x50&set=set1',
        job: 'Other specified disorders of synovium and tendon, hip',
        following: 5,
        id: '35a48a83-cbb9-482e-8272-e4c174876561',
      },
      {
        firstname: 'Kristin',
        lastname: 'Spencelayh',
        avatar_url: 'https://robohash.org/autaliasvelit.png?size=50x50&set=set1',
        job: 'Exposure of implanted urethral mesh into urethra, sequela',
        following: 57,
        id: '8a7a077f-ae87-4dc4-a04e-3fb9117a5f22',
      },
    ],
  },
  {
    id: '4126bd47-e425-4381-acdb-659e8ff11432',
    user: {
      firstname: 'Kordula',
      lastname: 'Klarzynski',
      avatar_url: 'https://robohash.org/sequiomnispariatur.png?size=50x50&set=set1',
      job: 'Automation Specialist III',
      following: 44,
    },
    created_at: '9/23/2022',
    description: 'Pathological fracture, l shoulder, subs for fx w delay heal',
    total_visits: 50,
    total_comments: 97,
    viewed_by: [
      {
        firstname: 'Torr',
        lastname: 'Otton',
        avatar_url: 'https://robohash.org/dignissimosblanditiisporro.png?size=50x50&set=set1',
        job: 'Subluxation of distal interphaln joint of l idx fngr, init',
        following: 75,
        id: '0ac4f080-e970-45f4-8018-ee97cedd8a77',
      },
    ],
  },
  {
    id: '381f8f23-0287-4b5b-af17-8c7acfe6b072',
    user: {
      firstname: 'Tiphani',
      lastname: 'Allchin',
      avatar_url: 'https://robohash.org/etquiaccusamus.png?size=50x50&set=set1',
      job: 'Quality Engineer',
      following: 62,
    },
    created_at: '8/7/2022',
    description: 'Open bite, right knee',
    total_visits: 77,
    total_comments: 26,
    viewed_by: [
      {
        firstname: 'Seth',
        lastname: 'Clayworth',
        avatar_url: 'https://robohash.org/eosomnisex.png?size=50x50&set=set1',
        job: 'Puncture wound with foreign body of left elbow',
        following: 4,
        id: '9dcb8fd8-4409-4473-bdd6-f8316334b77c',
      },
      {
        firstname: 'Frederica',
        lastname: 'Daubney',
        avatar_url: 'https://robohash.org/placeatitaquecupiditate.png?size=50x50&set=set1',
        job: 'Dislocation of proximal interphalangeal joint of left thumb',
        following: 60,
        id: '982a3e6b-b49e-46c9-b0b1-610796855746',
      },
      {
        firstname: 'Brew',
        lastname: 'Paulus',
        avatar_url: 'https://robohash.org/facilissuscipitminus.png?size=50x50&set=set1',
        job: 'Osteopathy after poliomyelitis, right forearm',
        following: 84,
        id: '23a1f3df-a3b7-4b73-abda-4810497f24cd',
      },
    ],
  },
  {
    id: 'b34aa68e-3d04-4f9a-a11a-7f760d22b421',
    user: {
      firstname: 'Sancho',
      lastname: 'Dybbe',
      avatar_url: 'https://robohash.org/doloribuscorporisvoluptate.png?size=50x50&set=set1',
      job: 'Editor',
      following: 70,
    },
    created_at: '6/13/2022',
    description: 'Exstrophy of urinary bladder',
    total_visits: 26,
    total_comments: 68,
    viewed_by: [
      {
        firstname: 'Rebbecca',
        lastname: 'Krol',
        avatar_url: 'https://robohash.org/undedebitislaudantium.png?size=50x50&set=set1',
        job: 'Laceration w/o foreign body of vagina and vulva, init encntr',
        following: 57,
        id: '011ce11c-a10f-42ac-b532-d8dbfa348834',
      },
      {
        firstname: 'Merilyn',
        lastname: 'Levings',
        avatar_url: 'https://robohash.org/deseruntmolestiaevel.png?size=50x50&set=set1',
        job: 'Unspecified superficial injury of other finger, init encntr',
        following: 82,
        id: 'a074aa26-cc30-40b8-9929-7c754364fcbf',
      },
      {
        firstname: 'Richard',
        lastname: 'Odney',
        avatar_url: 'https://robohash.org/rerumdoloripsam.png?size=50x50&set=set1',
        job: 'Unsp focal TBI w LOC >24 hr w/o ret consc w surv, init',
        following: 24,
        id: '68a5150b-3729-4c68-8bfb-9faab99d14f6',
      },
      {
        firstname: 'Christos',
        lastname: 'Streetfield',
        avatar_url: 'https://robohash.org/nonsuntveritatis.png?size=50x50&set=set1',
        job: 'Displ oblique fx shaft of unsp femr, 7thM',
        following: 69,
        id: 'e49f69a6-2b30-4d22-b202-3474ff8453c6',
      },
      {
        firstname: 'Lukas',
        lastname: 'Bickers',
        avatar_url: 'https://robohash.org/quibusdammagnamsimilique.png?size=50x50&set=set1',
        job: "Felty's syndrome, hip",
        following: 75,
        id: 'fb6c275c-919f-4daf-b165-504ea063cfee',
      },
    ],
  },
  {
    id: '5e87223c-6657-4e4a-a7b0-94c2e6ea5269',
    user: {
      firstname: 'Avrom',
      lastname: 'Avraam',
      avatar_url: 'https://robohash.org/estvoluptatesrerum.png?size=50x50&set=set1',
      job: 'Software Test Engineer IV',
      following: 15,
    },
    created_at: '7/10/2022',
    description: 'Lac w fb of back wall of thorax w/o penet thoracic cavity',
    total_visits: 15,
    total_comments: 53,
    viewed_by: [],
  },
  {
    id: '312248b8-1128-4ace-b201-0869f6d3834a',
    user: {
      firstname: 'Mirilla',
      lastname: 'Badini',
      avatar_url: 'https://robohash.org/nostrumquisquamautem.png?size=50x50&set=set1',
      job: 'Systems Administrator II',
      following: 100,
    },
    created_at: '6/19/2022',
    description: 'Subluxation of right scapula',
    total_visits: 6,
    total_comments: 13,
    viewed_by: [
      {
        firstname: 'Gregorio',
        lastname: 'Maly',
        avatar_url: 'https://robohash.org/culpaestmolestiae.png?size=50x50&set=set1',
        job: 'Pneumoconiosis due to asbestos and other mineral fibers',
        following: 52,
        id: '72e3e9c2-b082-4e91-84a9-6038ddeb8547',
      },
      {
        firstname: 'Sullivan',
        lastname: 'Keneleyside',
        avatar_url: 'https://robohash.org/nobisamollitia.png?size=50x50&set=set1',
        job: 'Unsp fx shaft of unsp ulna, 7thE',
        following: 72,
        id: '65fb2a1c-b572-41ab-b4e9-c4320d933009',
      },
      {
        firstname: 'Jonis',
        lastname: 'Leatt',
        avatar_url: 'https://robohash.org/explicaboeumat.png?size=50x50&set=set1',
        job: 'Disp fx of right tibial spine, subs for clos fx w nonunion',
        following: 27,
        id: 'f538740c-c7af-4499-bd17-06b6971311ef',
      },
    ],
  },
  {
    id: '0179cf66-c188-47a5-9959-a8a341116923',
    user: {
      firstname: 'Engelbert',
      lastname: 'Hutcheson',
      avatar_url: 'https://robohash.org/auterrorest.png?size=50x50&set=set1',
      job: 'Paralegal',
      following: 88,
    },
    created_at: '8/7/2022',
    description: 'Toxic effect of chloroform, undetermined, sequela',
    total_visits: 99,
    total_comments: 66,
    viewed_by: [
      {
        firstname: 'Brant',
        lastname: 'Kahen',
        avatar_url: 'https://robohash.org/adipiscisapientevoluptatem.png?size=50x50&set=set1',
        job: 'Nondisp fx of distal pole of navicular bone of right wrist',
        following: 79,
        id: '2e20d2a3-d51d-40d8-95f9-60ece7c38bed',
      },
      {
        firstname: 'Garv',
        lastname: 'Guillerman',
        avatar_url: 'https://robohash.org/quosquasivoluptate.png?size=50x50&set=set1',
        job: 'Pasngr in 3-whl mv inj in clsn w unsp mv nontraf, sequela',
        following: 74,
        id: '634cab49-0520-4dd5-bf75-caf63366e82b',
      },
    ],
  },
  {
    id: '58ed2e26-d9d5-48f1-b766-ba5bb1b801d1',
    user: {
      firstname: 'Winnah',
      lastname: 'Boomes',
      avatar_url: 'https://robohash.org/numquamidsunt.png?size=50x50&set=set1',
      job: 'Legal Assistant',
      following: 66,
    },
    created_at: '11/8/2022',
    description: 'Digestants',
    total_visits: 4,
    total_comments: 28,
    viewed_by: [
      {
        firstname: 'Fleming',
        lastname: 'Ovitts',
        avatar_url: 'https://robohash.org/autvoluptasvoluptas.png?size=50x50&set=set1',
        job: 'Other specified rheumatoid arthritis, left elbow',
        following: 74,
        id: '060410d1-f09e-4500-9b84-0e49dac83fc7',
      },
    ],
  },
  {
    id: 'bd228429-09d2-48ca-a4df-df809ff596c1',
    user: {
      firstname: 'Sandro',
      lastname: 'Tassaker',
      avatar_url: 'https://robohash.org/estiureillum.png?size=50x50&set=set1',
      job: 'Speech Pathologist',
      following: 87,
    },
    created_at: '2/4/2022',
    description: 'Displ transverse fx shaft of l femr, 7thP',
    total_visits: 15,
    total_comments: 89,
    viewed_by: [],
  },
  {
    id: 'dbad9289-1beb-446c-99f9-a8e7067eb187',
    user: {
      firstname: 'Warren',
      lastname: 'MacEllen',
      avatar_url: 'https://robohash.org/quovoluptatemearum.png?size=50x50&set=set1',
      job: 'Desktop Support Technician',
      following: 88,
    },
    created_at: '7/11/2022',
    description: 'Underdosing of local anesthetics, subsequent encounter',
    total_visits: 87,
    total_comments: 79,
    viewed_by: [
      {
        firstname: 'Dani',
        lastname: 'Vautre',
        avatar_url: 'https://robohash.org/eossintea.png?size=50x50&set=set1',
        job: 'Oth injury due to oth accident to inflatbl crft, init',
        following: 5,
        id: '41f884b8-d17e-428a-b118-7222afbd3802',
      },
      {
        firstname: 'Pepita',
        lastname: 'Kelf',
        avatar_url: 'https://robohash.org/quibusdamnihilpariatur.png?size=50x50&set=set1',
        job: 'Displ transverse fx shaft of l ulna, 7thH',
        following: 70,
        id: '9daecd58-7481-4f42-a92c-40100a548fe3',
      },
      {
        firstname: 'Fremont',
        lastname: 'Marlin',
        avatar_url: 'https://robohash.org/aliquamatdeleniti.png?size=50x50&set=set1',
        job: 'Oth disp fx of fourth cervcal vert, subs for fx w delay heal',
        following: 41,
        id: 'ee64bc5e-690b-405f-9202-5e44ae10124d',
      },
    ],
  },
  {
    id: '5c45c149-4874-4140-bc1a-871eb786a815',
    user: {
      firstname: 'Angeline',
      lastname: 'Nott',
      avatar_url: 'https://robohash.org/voluptateundeut.png?size=50x50&set=set1',
      job: 'Desktop Support Technician',
      following: 25,
    },
    created_at: '11/16/2022',
    description: 'Malignant neoplasm of unspecified part of adrenal gland',
    total_visits: 12,
    total_comments: 16,
    viewed_by: [
      {
        firstname: 'Sigrid',
        lastname: 'Malacrida',
        avatar_url: 'https://robohash.org/sequipariaturullam.png?size=50x50&set=set1',
        job: 'Unsp car occupant injured in clsn w pedl cyc in traf, subs',
        following: 53,
        id: '88417306-1f1e-47a9-b38c-60568fb160f4',
      },
      {
        firstname: 'Jillene',
        lastname: 'Rickert',
        avatar_url: 'https://robohash.org/quiaasperioresconsequatur.png?size=50x50&set=set1',
        job: 'Partial traumatic MCP amputation of right index finger',
        following: 93,
        id: '15cbfe92-d711-4af5-8afa-a14f26d3dcbf',
      },
      {
        firstname: 'Ralph',
        lastname: "O' Connell",
        avatar_url: 'https://robohash.org/asperioresmaximebeatae.png?size=50x50&set=set1',
        job: 'Toxic effect of other metals, intentional self-harm',
        following: 67,
        id: '90db75c7-2107-4cab-b04a-6336fc5f98f2',
      },
      {
        firstname: 'Oren',
        lastname: 'Braidwood',
        avatar_url: 'https://robohash.org/enimtemporaeos.png?size=50x50&set=set1',
        job: 'Nondisp suprcndl fx w intrcndl extn low end l femr, 7thB',
        following: 68,
        id: '0f3af2fc-1e1f-4206-bd5d-acff400d9732',
      },
      {
        firstname: 'Ambrosi',
        lastname: 'Newlin',
        avatar_url: 'https://robohash.org/vitaeaspernaturat.png?size=50x50&set=set1',
        job: 'Inj flexor musc/fasc/tend r mid finger at forarm lv, init',
        following: 71,
        id: '1b062c90-90a4-47aa-b716-36f30f1d8d62',
      },
    ],
  },
  {
    id: '481de944-4241-4507-9160-09d851d84780',
    user: {
      firstname: 'Tessa',
      lastname: 'Godfrey',
      avatar_url: 'https://robohash.org/etomnisplaceat.png?size=50x50&set=set1',
      job: 'Automation Specialist II',
      following: 35,
    },
    created_at: '4/2/2022',
    description: 'Carcinoma in situ of other urinary organs',
    total_visits: 41,
    total_comments: 34,
    viewed_by: [
      {
        firstname: 'Helaine',
        lastname: 'Pover',
        avatar_url: 'https://robohash.org/oditidmodi.png?size=50x50&set=set1',
        job: 'Blister (nonthermal), right thigh, initial encounter',
        following: 55,
        id: '35c79bf5-fcb0-4e9f-b478-f04a0809ce93',
      },
      {
        firstname: 'Ginger',
        lastname: 'Ervin',
        avatar_url: 'https://robohash.org/quofugiatquae.png?size=50x50&set=set1',
        job: 'War op involving unsp fire/conflagr/hot subst, milt, subs',
        following: 23,
        id: 'a147cbc3-88a8-4696-9318-8237bc232e67',
      },
      {
        firstname: 'Krysta',
        lastname: 'Chesson',
        avatar_url: 'https://robohash.org/uteaat.png?size=50x50&set=set1',
        job: "Reiter's disease, shoulder",
        following: 100,
        id: '2f960b33-3d41-4ec0-8e59-56be352e4895',
      },
    ],
  },
];
