export default [
  {
    id: '1a0ab718-3c6b-4d35-a6fd-aa701c1eab06',
    user: {
      firstname: 'Faber',
      lastname: 'Wyllcock',
      avatar_url: 'https://robohash.org/excepturifacerevero.png?size=50x50&set=set1',
      job: 'Dental Hygienist',
      following: true,
    },
    created_at: '11/8/2022',
    description:
      'Diabetes mellitus due to underlying condition with proliferative diabetic retinopathy with macular edema, bilateral',
    total_visits: 419,
    total_comments: 324,
    viewed_by: [
      {
        firstname: 'Dyane',
        lastname: 'Duns',
        avatar_url: 'https://robohash.org/areprehenderitlaudantium.png?size=50x50&set=set1',
        job: 'Software Test Engineer I',
        following: false,
        id: '38b1166a-64a0-484d-8f58-9db645850797',
      },
      {
        firstname: 'Mikol',
        lastname: 'Mowat',
        avatar_url: 'https://robohash.org/explicaboreprehenderitillo.png?size=50x50&set=set1',
        job: 'Software Engineer II',
        following: false,
        id: '9567b262-7f7f-4de4-bb7d-047eea73e602',
      },
      {
        firstname: 'Dani',
        lastname: 'Heinke',
        avatar_url: 'https://robohash.org/nihileumcupiditate.png?size=50x50&set=set1',
        job: 'Senior Developer',
        following: false,
        id: '52ff7cf3-c6de-40fe-a800-e843460cbc15',
      },
      {
        firstname: 'Rasla',
        lastname: 'Vasechkin',
        avatar_url: 'https://robohash.org/delectusmagninobis.png?size=50x50&set=set1',
        job: 'Director of Sales',
        following: false,
        id: '796bc827-ac2f-4a4c-808a-3441fca6d28f',
      },
      {
        firstname: 'Nappy',
        lastname: 'Lowdiane',
        avatar_url: 'https://robohash.org/eosvoluptatemdelectus.png?size=50x50&set=set1',
        job: 'Mechanical Systems Engineer',
        following: false,
        id: 'b79e17fe-26c7-4693-a783-30edce070ef7',
      },
    ],
  },
  {
    id: '8da22a20-78f7-4a7b-9e22-8f8467d290f5',
    user: {
      firstname: 'Jordanna',
      lastname: 'Alderwick',
      avatar_url: 'https://robohash.org/adquastempore.png?size=50x50&set=set1',
      job: 'Project Manager',
      following: true,
    },
    created_at: '6/9/2022',
    description: 'Posterior dislocation of right ulnohumeral joint, subsequent encounter',
    total_visits: 596,
    total_comments: 821,
    viewed_by: [
      {
        firstname: 'Gratia',
        lastname: 'Klosser',
        avatar_url: 'https://robohash.org/molestiaesedest.png?size=50x50&set=set1',
        job: 'Design Engineer',
        following: true,
        id: 'f87dec4e-42c7-498c-b8d9-59627b443193',
      },
      {
        firstname: 'Nikola',
        lastname: 'Royal',
        avatar_url: 'https://robohash.org/excepturinonut.png?size=50x50&set=set1',
        job: 'Actuary',
        following: false,
        id: '6a6a5235-9448-40b2-9d05-1aa4137cada8',
      },
      {
        firstname: 'Alley',
        lastname: 'Abrahamowitcz',
        avatar_url: 'https://robohash.org/nondoloresfugit.png?size=50x50&set=set1',
        job: 'Biostatistician III',
        following: true,
        id: '75d23bf1-8968-438b-a039-263bad0ab6f0',
      },
      {
        firstname: 'Marc',
        lastname: 'Hargroves',
        avatar_url: 'https://robohash.org/oditdignissimosnihil.png?size=50x50&set=set1',
        job: 'Administrative Assistant IV',
        following: true,
        id: '86a20fce-b7c2-4651-bac3-1c8903d4b681',
      },
      {
        firstname: 'Geraldine',
        lastname: 'Cornhill',
        avatar_url: 'https://robohash.org/adquiminus.png?size=50x50&set=set1',
        job: 'Senior Sales Associate',
        following: false,
        id: 'b3b74c9a-bb9a-4a48-9176-2a897dfd3f4f',
      },
      {
        firstname: 'Luella',
        lastname: 'Vallender',
        avatar_url: 'https://robohash.org/doloribusetrerum.png?size=50x50&set=set1',
        job: 'Budget/Accounting Analyst III',
        following: false,
        id: 'd7fa185d-e7a0-4b18-abfb-53ba48405bf6',
      },
      {
        firstname: 'Michal',
        lastname: 'Ledward',
        avatar_url: 'https://robohash.org/omnisdeseruntex.png?size=50x50&set=set1',
        job: 'Data Coordiator',
        following: false,
        id: 'fda1da4c-6b72-4b43-a8fc-4f119b7908c3',
      },
    ],
  },
  {
    id: 'e42901f7-98f3-41b5-a9f4-3b4466e16f3a',
    user: {
      firstname: 'Alexandr',
      lastname: 'Gypps',
      avatar_url: 'https://robohash.org/velitnihilpossimus.png?size=50x50&set=set1',
      job: 'Business Systems Development Analyst',
      following: true,
    },
    created_at: '3/12/2022',
    description:
      'Burn of third degree of unspecified site of left lower limb, except ankle and foot, initial encounter',
    total_visits: 734,
    total_comments: 55,
    viewed_by: [],
  },
  {
    id: 'aeb9c85e-0d11-4e14-9416-c8a827a33a72',
    user: {
      firstname: 'Lilli',
      lastname: 'Pettecrew',
      avatar_url: 'https://robohash.org/repellendusquisqui.png?size=50x50&set=set1',
      job: 'Director of Sales',
      following: false,
    },
    created_at: '10/11/2022',
    description: 'Assault by pushing or placing victim in front of moving object',
    total_visits: 187,
    total_comments: 524,
    viewed_by: [
      {
        firstname: 'Tracy',
        lastname: 'Sidle',
        avatar_url: 'https://robohash.org/doloremquesequibeatae.png?size=50x50&set=set1',
        job: 'General Manager',
        following: false,
        id: '95823aa0-85ff-4b26-8fa6-61d0efe24c07',
      },
      {
        firstname: 'Ursulina',
        lastname: 'Peachey',
        avatar_url: 'https://robohash.org/culpaeosquaerat.png?size=50x50&set=set1',
        job: 'Marketing Manager',
        following: true,
        id: 'af5d1d5e-9610-4a67-90c9-4a49454ff677',
      },
      {
        firstname: 'Kipper',
        lastname: 'Boulsher',
        avatar_url: 'https://robohash.org/quivitaeporro.png?size=50x50&set=set1',
        job: 'Sales Associate',
        following: false,
        id: '21b8d775-c1b3-4b79-b43b-123b1bc10baa',
      },
      {
        firstname: 'Jaquelin',
        lastname: 'Rabjohn',
        avatar_url: 'https://robohash.org/eligendisuntconsequuntur.png?size=50x50&set=set1',
        job: 'Senior Cost Accountant',
        following: true,
        id: 'df300936-602c-4a5d-8e45-e4d1211360a7',
      },
      {
        firstname: 'Carmelita',
        lastname: 'Muncie',
        avatar_url: 'https://robohash.org/suntquibusdamnulla.png?size=50x50&set=set1',
        job: 'Compensation Analyst',
        following: false,
        id: 'fc112a12-4245-45de-9267-aa02dfeb386c',
      },
      {
        firstname: 'Lorilyn',
        lastname: 'Neely',
        avatar_url: 'https://robohash.org/doloresdoloremqueexercitationem.png?size=50x50&set=set1',
        job: 'Staff Scientist',
        following: false,
        id: '36d629ad-e850-4bf8-b3a1-cef2d921c9e8',
      },
      {
        firstname: 'Jillene',
        lastname: 'Dries',
        avatar_url: 'https://robohash.org/temporibusquisquamnatus.png?size=50x50&set=set1',
        job: 'Senior Developer',
        following: true,
        id: '5a061ef2-38f2-4fb6-aef2-ce8ec50e9bc3',
      },
      {
        firstname: 'Lock',
        lastname: 'Cestard',
        avatar_url: 'https://robohash.org/quaeratnihilsed.png?size=50x50&set=set1',
        job: 'Registered Nurse',
        following: true,
        id: 'e6233156-a931-4109-aedb-5c6c23d90224',
      },
      {
        firstname: 'Costa',
        lastname: 'Krook',
        avatar_url: 'https://robohash.org/nemodoloremquia.png?size=50x50&set=set1',
        job: 'Compensation Analyst',
        following: true,
        id: '7473441e-96c6-46f9-9740-aa56dd75194a',
      },
      {
        firstname: 'Maison',
        lastname: 'Bulteel',
        avatar_url: 'https://robohash.org/velquiaautem.png?size=50x50&set=set1',
        job: 'Speech Pathologist',
        following: true,
        id: '2ca1c8fa-df4b-424f-af58-07fe43c99f3d',
      },
    ],
  },
  {
    id: 'ed212956-34a6-4009-bb77-5890b06979f1',
    user: {
      firstname: 'Domingo',
      lastname: 'Drinkale',
      avatar_url: 'https://robohash.org/quamdolorererum.png?size=50x50&set=set1',
      job: 'Structural Engineer',
      following: false,
    },
    created_at: '2/11/2022',
    description:
      'Driver of three-wheeled motor vehicle injured in collision with other nonmotor vehicle in traffic accident, initial encounter',
    total_visits: 106,
    total_comments: 242,
    viewed_by: [],
  },
  {
    id: '06ff387f-8f0b-4ed8-85b7-352c5194b8eb',
    user: {
      firstname: 'Erminie',
      lastname: 'Lindmark',
      avatar_url: 'https://robohash.org/inventoredoloresaliquam.png?size=50x50&set=set1',
      job: 'GIS Technical Architect',
      following: false,
    },
    created_at: '9/19/2022',
    description:
      'Nondisplaced spiral fracture of shaft of unspecified tibia, initial encounter for open fracture type I or II',
    total_visits: 316,
    total_comments: 895,
    viewed_by: [
      {
        firstname: 'Celestina',
        lastname: 'McIntee',
        avatar_url: 'https://robohash.org/utsitneque.png?size=50x50&set=set1',
        job: 'Legal Assistant',
        following: false,
        id: '536cacc0-0575-4396-b6c9-33d3b3d4185a',
      },
      {
        firstname: 'Norrie',
        lastname: 'Winstanley',
        avatar_url: 'https://robohash.org/utrecusandaeenim.png?size=50x50&set=set1',
        job: 'Human Resources Manager',
        following: false,
        id: 'f435f1b2-7e78-4d8e-84a5-89a98d5ef9fa',
      },
      {
        firstname: 'Karla',
        lastname: 'Bellow',
        avatar_url: 'https://robohash.org/doloremolestiaeducimus.png?size=50x50&set=set1',
        job: 'Staff Accountant III',
        following: true,
        id: '1550bfa4-f870-4f1c-91fc-0b62d2cf148b',
      },
      {
        firstname: 'Uta',
        lastname: 'MacColm',
        avatar_url: 'https://robohash.org/beataesimiliquequas.png?size=50x50&set=set1',
        job: 'Assistant Media Planner',
        following: true,
        id: '69cc421e-3ca4-4530-8727-92ba9f6cbecb',
      },
      {
        firstname: 'Dionysus',
        lastname: 'Yakob',
        avatar_url: 'https://robohash.org/idaliquidfacilis.png?size=50x50&set=set1',
        job: 'Payment Adjustment Coordinator',
        following: true,
        id: 'ccab4758-3246-4ae2-9fbf-ddddacb9ee81',
      },
      {
        firstname: 'Agnes',
        lastname: 'Henri',
        avatar_url: 'https://robohash.org/estprovidentut.png?size=50x50&set=set1',
        job: 'Software Test Engineer I',
        following: true,
        id: 'ae83c977-162f-4000-908c-7cb5803e406d',
      },
      {
        firstname: 'Gerik',
        lastname: 'Alves',
        avatar_url: 'https://robohash.org/utfugitomnis.png?size=50x50&set=set1',
        job: 'Actuary',
        following: false,
        id: 'b5433b50-deda-4796-ad8f-c93cd0b3d839',
      },
      {
        firstname: 'Bernetta',
        lastname: 'Simmers',
        avatar_url: 'https://robohash.org/perferendisitaqueporro.png?size=50x50&set=set1',
        job: 'Information Systems Manager',
        following: true,
        id: 'aa7b81f8-088e-443c-b088-4581b1e62a85',
      },
      {
        firstname: 'Nerty',
        lastname: 'Ducket',
        avatar_url: 'https://robohash.org/solutaquiexplicabo.png?size=50x50&set=set1',
        job: 'Office Assistant IV',
        following: true,
        id: '0884a1bb-b50e-4e34-aaf0-498c22e7cb1a',
      },
    ],
  },
  {
    id: '6e760b79-11a4-4c05-aa08-b8d9fccf4aae',
    user: {
      firstname: 'Germaine',
      lastname: 'Timny',
      avatar_url: 'https://robohash.org/praesentiummolestiassit.png?size=50x50&set=set1',
      job: 'Statistician II',
      following: true,
    },
    created_at: '10/17/2022',
    description: 'Flail chest, initial encounter for closed fracture',
    total_visits: 107,
    total_comments: 723,
    viewed_by: [
      {
        firstname: 'Veradis',
        lastname: 'Danielian',
        avatar_url: 'https://robohash.org/suscipitutqui.png?size=50x50&set=set1',
        job: 'Social Worker',
        following: true,
        id: '9f8b6b09-b98b-4700-94c3-88871ea2627d',
      },
      {
        firstname: 'Clark',
        lastname: 'Agar',
        avatar_url: 'https://robohash.org/dolorumestlabore.png?size=50x50&set=set1',
        job: 'Electrical Engineer',
        following: true,
        id: 'cf3bec6f-c1d0-4c16-85c9-a5a2cfdea6c3',
      },
      {
        firstname: 'Clary',
        lastname: 'Crosoer',
        avatar_url: 'https://robohash.org/quiasitaccusamus.png?size=50x50&set=set1',
        job: 'Help Desk Technician',
        following: false,
        id: '6fb7dfdd-2dd6-40a5-b0e2-425cb4afdeb5',
      },
      {
        firstname: 'Friedrick',
        lastname: 'Mingaye',
        avatar_url: 'https://robohash.org/solutasimiliqueet.png?size=50x50&set=set1',
        job: 'VP Product Management',
        following: true,
        id: 'c9f2220f-b9f9-431b-9d27-aabd17d29aea',
      },
      {
        firstname: 'Sharron',
        lastname: 'Morde',
        avatar_url: 'https://robohash.org/essequidemet.png?size=50x50&set=set1',
        job: 'Recruiter',
        following: false,
        id: '61db65f0-35ce-4fa8-ab4b-8c37c444306f',
      },
      {
        firstname: 'Carole',
        lastname: 'Ardron',
        avatar_url: 'https://robohash.org/velperspiciatisex.png?size=50x50&set=set1',
        job: 'Statistician IV',
        following: false,
        id: '1a78209d-b74d-413b-ae60-b2ac773b4063',
      },
      {
        firstname: 'Pepe',
        lastname: 'Ivanikov',
        avatar_url: 'https://robohash.org/harumaperiamvelit.png?size=50x50&set=set1',
        job: 'Editor',
        following: false,
        id: '94dd6e24-5083-4264-80c4-0f878d9d1c62',
      },
      {
        firstname: 'Aloysia',
        lastname: 'Andrys',
        avatar_url: 'https://robohash.org/excepturiveniamvoluptatum.png?size=50x50&set=set1',
        job: 'Pharmacist',
        following: false,
        id: 'd42c4f9d-cdf6-4cb9-8e83-340b4df161f8',
      },
      {
        firstname: 'Goldina',
        lastname: 'Gove',
        avatar_url: 'https://robohash.org/consequunturteneturet.png?size=50x50&set=set1',
        job: 'Data Coordiator',
        following: true,
        id: '120ec19d-74b2-4e0a-8ebd-f5e74058742b',
      },
      {
        firstname: 'Olive',
        lastname: 'Doman',
        avatar_url: 'https://robohash.org/solutarecusandaeet.png?size=50x50&set=set1',
        job: 'Computer Systems Analyst III',
        following: false,
        id: '31cb51fb-0295-4fea-9c4d-df1c47bdaa21',
      },
    ],
  },
  {
    id: '226f2c64-9374-441e-a419-9078631ec59e',
    user: {
      firstname: 'Mord',
      lastname: 'Bruneton',
      avatar_url: 'https://robohash.org/eteligendiratione.png?size=50x50&set=set1',
      job: 'Dental Hygienist',
      following: true,
    },
    created_at: '9/28/2022',
    description: 'Other place in mobile home as the place of occurrence of the external cause',
    total_visits: 496,
    total_comments: 39,
    viewed_by: [
      {
        firstname: 'Nikolai',
        lastname: 'Swarbrick',
        avatar_url: 'https://robohash.org/veldolorumqui.png?size=50x50&set=set1',
        job: 'Legal Assistant',
        following: false,
        id: '361512c7-de9c-4e44-8449-127f5922fcb7',
      },
      {
        firstname: 'Urban',
        lastname: 'Cristoferi',
        avatar_url: 'https://robohash.org/omnissimiliquenemo.png?size=50x50&set=set1',
        job: 'VP Product Management',
        following: true,
        id: '4035684b-5daa-40ff-b439-e55fcbe41b08',
      },
    ],
  },
  {
    id: '8203bae4-a2c4-44f7-b60d-718efec59b07',
    user: {
      firstname: 'Jacinthe',
      lastname: 'Lynas',
      avatar_url: 'https://robohash.org/cumqueexercitationemconsequatur.png?size=50x50&set=set1',
      job: 'Nurse Practicioner',
      following: true,
    },
    created_at: '12/18/2021',
    description: 'Injury of other nerves at wrist and hand level of right arm',
    total_visits: 795,
    total_comments: 311,
    viewed_by: [
      {
        firstname: 'Kipp',
        lastname: 'Gonnard',
        avatar_url: 'https://robohash.org/officianamimpedit.png?size=50x50&set=set1',
        job: 'VP Accounting',
        following: true,
        id: 'b20c34bd-726f-4bef-b645-1b72c8fbf51c',
      },
      {
        firstname: 'Amber',
        lastname: 'Houchen',
        avatar_url: 'https://robohash.org/dictarerumculpa.png?size=50x50&set=set1',
        job: 'Accountant III',
        following: false,
        id: '81c97423-1119-4423-8b93-9f035adb3d1d',
      },
      {
        firstname: 'Daryn',
        lastname: 'Cheley',
        avatar_url: 'https://robohash.org/doloremquerepellatomnis.png?size=50x50&set=set1',
        job: 'Clinical Specialist',
        following: true,
        id: 'f215acbb-8934-4ae1-b399-56eedd17eb8d',
      },
      {
        firstname: 'Steward',
        lastname: 'Almey',
        avatar_url: 'https://robohash.org/velfugaprovident.png?size=50x50&set=set1',
        job: 'Nuclear Power Engineer',
        following: false,
        id: '56346a31-bfeb-4bad-b167-5fd1d7b3fa4f',
      },
      {
        firstname: 'Mandel',
        lastname: 'Swynley',
        avatar_url: 'https://robohash.org/doloredignissimoseligendi.png?size=50x50&set=set1',
        job: 'Developer III',
        following: false,
        id: '66ee6be0-5c08-46c5-ba48-6a33ade7784d',
      },
      {
        firstname: 'Remington',
        lastname: 'Cowup',
        avatar_url: 'https://robohash.org/fugiatpraesentiumarchitecto.png?size=50x50&set=set1',
        job: 'Desktop Support Technician',
        following: true,
        id: 'acb847ab-5b70-4821-a3f6-d3b677645115',
      },
      {
        firstname: 'Abey',
        lastname: 'Pollen',
        avatar_url: 'https://robohash.org/voluptasreiciendismolestias.png?size=50x50&set=set1',
        job: 'Graphic Designer',
        following: true,
        id: '49a69b05-60fa-4ff1-a807-a76c3940cfb7',
      },
      {
        firstname: 'Inge',
        lastname: 'Dashkov',
        avatar_url: 'https://robohash.org/quaesimiliquenulla.png?size=50x50&set=set1',
        job: 'Payment Adjustment Coordinator',
        following: false,
        id: '92ff0674-2efe-47d9-91b4-a11d9c560d4a',
      },
      {
        firstname: 'Delainey',
        lastname: 'Pettingall',
        avatar_url: 'https://robohash.org/hicvoluptateest.png?size=50x50&set=set1',
        job: 'Programmer II',
        following: true,
        id: 'fea5d192-8cce-4021-9d48-e602043314fb',
      },
    ],
  },
  {
    id: 'fff69fa0-96b8-4f53-ac08-7a8154b72e71',
    user: {
      firstname: 'Jorie',
      lastname: 'Labone',
      avatar_url: 'https://robohash.org/eumquibusdamratione.png?size=50x50&set=set1',
      job: 'Health Coach IV',
      following: false,
    },
    created_at: '7/9/2022',
    description: 'Other specified injuries of right lower leg, sequela',
    total_visits: 673,
    total_comments: 800,
    viewed_by: [
      {
        firstname: 'Baillie',
        lastname: 'Duckit',
        avatar_url: 'https://robohash.org/sitquasifacere.png?size=50x50&set=set1',
        job: 'Analog Circuit Design manager',
        following: false,
        id: '873d0004-721c-47a2-9763-a21be0c2f6a7',
      },
      {
        firstname: 'Wally',
        lastname: 'Tummons',
        avatar_url: 'https://robohash.org/dolorenullaest.png?size=50x50&set=set1',
        job: 'Financial Advisor',
        following: true,
        id: 'f86b96f1-7955-408f-a76f-efe50c91d7cd',
      },
      {
        firstname: 'Selena',
        lastname: 'Endon',
        avatar_url: 'https://robohash.org/autipsumrecusandae.png?size=50x50&set=set1',
        job: 'Editor',
        following: true,
        id: '9b0ea2c2-b8e4-4c24-a669-f2a682f659d9',
      },
      {
        firstname: 'Orrin',
        lastname: 'Emeney',
        avatar_url: 'https://robohash.org/quameumdeleniti.png?size=50x50&set=set1',
        job: 'Account Executive',
        following: false,
        id: '049bfa68-7827-49fc-bf83-2fb8905bef99',
      },
      {
        firstname: 'Iona',
        lastname: 'Blundell',
        avatar_url: 'https://robohash.org/autautconsequatur.png?size=50x50&set=set1',
        job: 'Administrative Assistant III',
        following: true,
        id: '84c90901-f4b3-4ab9-b117-26cf336f82e5',
      },
      {
        firstname: 'Gerianna',
        lastname: 'Bampton',
        avatar_url: 'https://robohash.org/dolorvoluptatequi.png?size=50x50&set=set1',
        job: 'Environmental Specialist',
        following: false,
        id: '5ac7011b-25a0-430b-a1b1-67aa18694ab8',
      },
      {
        firstname: 'Horatio',
        lastname: 'Bastide',
        avatar_url: 'https://robohash.org/idhicrepudiandae.png?size=50x50&set=set1',
        job: 'Editor',
        following: false,
        id: '30734882-4849-4c56-9f84-eebf70a5ea09',
      },
    ],
  },
  {
    id: 'a88fa580-c7ce-4644-9ac5-2324c1d71a4d',
    user: {
      firstname: 'Dorey',
      lastname: 'Simkins',
      avatar_url: 'https://robohash.org/numquaminnon.png?size=50x50&set=set1',
      job: 'Sales Associate',
      following: false,
    },
    created_at: '7/10/2022',
    description: 'Partial traumatic amputation at level between left shoulder and elbow',
    total_visits: 107,
    total_comments: 815,
    viewed_by: [
      {
        firstname: 'Nikkie',
        lastname: 'Yushankin',
        avatar_url: 'https://robohash.org/estremomnis.png?size=50x50&set=set1',
        job: 'Teacher',
        following: false,
        id: '1ad86c6d-5430-4a6c-b89f-48106d6119ce',
      },
      {
        firstname: 'Fanchon',
        lastname: 'Baynom',
        avatar_url: 'https://robohash.org/evenietlaudantiumnon.png?size=50x50&set=set1',
        job: 'Registered Nurse',
        following: true,
        id: '0d795577-ec2f-47b7-b67d-4e0365890568',
      },
      {
        firstname: 'Talya',
        lastname: 'Goodbur',
        avatar_url: 'https://robohash.org/explicabodelectusmollitia.png?size=50x50&set=set1',
        job: 'Senior Quality Engineer',
        following: true,
        id: 'd2385619-148b-4296-985b-6e10cc0cbd60',
      },
      {
        firstname: 'Murray',
        lastname: 'Rickhuss',
        avatar_url: 'https://robohash.org/quiassumendaincidunt.png?size=50x50&set=set1',
        job: 'Staff Accountant III',
        following: true,
        id: 'a6cd18e5-61a4-48e0-9c49-28b74aad0b7e',
      },
      {
        firstname: 'Matthus',
        lastname: 'Gaylor',
        avatar_url: 'https://robohash.org/rerumliberoconsectetur.png?size=50x50&set=set1',
        job: 'Administrative Officer',
        following: false,
        id: '75b34985-314b-4226-a447-e838b81952fc',
      },
      {
        firstname: 'Zach',
        lastname: 'Howkins',
        avatar_url: 'https://robohash.org/nihileumperspiciatis.png?size=50x50&set=set1',
        job: 'Administrative Officer',
        following: true,
        id: 'a9966d34-e72e-4f12-87e1-73ca014a07d5',
      },
      {
        firstname: 'Prissie',
        lastname: 'Thews',
        avatar_url: 'https://robohash.org/perspiciatisestrepellendus.png?size=50x50&set=set1',
        job: 'Geological Engineer',
        following: true,
        id: '95cfbe56-a750-4775-98d2-41e81aa952a4',
      },
      {
        firstname: 'Stephannie',
        lastname: 'Blunsom',
        avatar_url: 'https://robohash.org/quisaccusamusaut.png?size=50x50&set=set1',
        job: 'Librarian',
        following: true,
        id: 'b74826e5-36d4-4c1b-9de0-aa201a064451',
      },
    ],
  },
  {
    id: '4e34faa7-9905-4252-b4bf-176bd114d3a9',
    user: {
      firstname: 'Aimee',
      lastname: 'Pickin',
      avatar_url: 'https://robohash.org/quaeetquia.png?size=50x50&set=set1',
      job: 'Technical Writer',
      following: false,
    },
    created_at: '5/6/2022',
    description: 'Encounter for screening for infectious and parasitic diseases, unspecified',
    total_visits: 769,
    total_comments: 12,
    viewed_by: [
      {
        firstname: 'Fredelia',
        lastname: 'Dugget',
        avatar_url: 'https://robohash.org/velitundetempora.png?size=50x50&set=set1',
        job: 'Financial Advisor',
        following: true,
        id: 'bc498de3-d5d6-431f-93e2-ef22060dded8',
      },
      {
        firstname: 'Olivero',
        lastname: 'Dagleas',
        avatar_url: 'https://robohash.org/sintdolorumnulla.png?size=50x50&set=set1',
        job: 'Web Developer III',
        following: true,
        id: '4399d79f-bcec-4eeb-90e8-43cd0c9acaf7',
      },
      {
        firstname: 'Salaidh',
        lastname: 'Marrable',
        avatar_url: 'https://robohash.org/etsequilaudantium.png?size=50x50&set=set1',
        job: 'Senior Sales Associate',
        following: false,
        id: '90df7b5c-84cf-447e-99a1-0eff2154c780',
      },
      {
        firstname: 'Lexy',
        lastname: 'Boyle',
        avatar_url: 'https://robohash.org/hicmollitiaat.png?size=50x50&set=set1',
        job: 'Data Coordiator',
        following: false,
        id: '66eb52a4-e0e5-4b8b-ad72-5f4bd2f33572',
      },
    ],
  },
  {
    id: 'c6f2d833-a86e-41db-bdf4-a08e51f8c62c',
    user: {
      firstname: 'Meyer',
      lastname: 'Zealey',
      avatar_url: 'https://robohash.org/dictamagnameaque.png?size=50x50&set=set1',
      job: 'Developer I',
      following: true,
    },
    created_at: '8/24/2022',
    description: 'Posterior dislocation of right humerus, subsequent encounter',
    total_visits: 940,
    total_comments: 591,
    viewed_by: [],
  },
  {
    id: '3a7eb8b4-8a59-466e-aa97-36b23c409b92',
    user: {
      firstname: 'Madel',
      lastname: 'Gambrell',
      avatar_url: 'https://robohash.org/evenietdoloremnon.png?size=50x50&set=set1',
      job: 'Software Test Engineer I',
      following: true,
    },
    created_at: '10/17/2022',
    description: 'Injury of other nerves at forearm level, unspecified arm, subsequent encounter',
    total_visits: 748,
    total_comments: 731,
    viewed_by: [
      {
        firstname: 'Herve',
        lastname: 'Longhirst',
        avatar_url: 'https://robohash.org/autemquasifacere.png?size=50x50&set=set1',
        job: 'Database Administrator II',
        following: false,
        id: 'a72591de-d2cf-422e-9b30-9602770a8e8c',
      },
      {
        firstname: 'Niki',
        lastname: 'Adicot',
        avatar_url: 'https://robohash.org/quialiquidcumque.png?size=50x50&set=set1',
        job: 'Account Executive',
        following: false,
        id: 'e481207b-7ea9-4f0b-ae56-8c98b4232989',
      },
      {
        firstname: 'Freda',
        lastname: 'Stanfield',
        avatar_url: 'https://robohash.org/remquoddolor.png?size=50x50&set=set1',
        job: 'Web Developer III',
        following: true,
        id: '2239f7cf-26e7-4f2a-bc9f-5c4c30153a02',
      },
    ],
  },
  {
    id: 'b228b313-1d07-48aa-9015-7aad75996de7',
    user: {
      firstname: 'Faye',
      lastname: 'McMorran',
      avatar_url: 'https://robohash.org/illumesteius.png?size=50x50&set=set1',
      job: 'Community Outreach Specialist',
      following: true,
    },
    created_at: '5/4/2022',
    description: 'Unspecified fracture of unspecified acetabulum, sequela',
    total_visits: 263,
    total_comments: 905,
    viewed_by: [
      {
        firstname: 'Lonni',
        lastname: 'Crayker',
        avatar_url: 'https://robohash.org/expeditavoluptasvoluptatum.png?size=50x50&set=set1',
        job: 'Structural Analysis Engineer',
        following: false,
        id: '318ba793-25f5-4334-b441-4434ba303cd7',
      },
      {
        firstname: 'Lorraine',
        lastname: 'Eade',
        avatar_url: 'https://robohash.org/quasiullamet.png?size=50x50&set=set1',
        job: 'VP Sales',
        following: false,
        id: 'd6f32d33-72af-4c39-9244-edf70ac9c9d6',
      },
      {
        firstname: 'Mollee',
        lastname: 'Horrell',
        avatar_url: 'https://robohash.org/minimasuscipitdolores.png?size=50x50&set=set1',
        job: 'Account Executive',
        following: false,
        id: '58b94954-d318-437c-a907-b908a9d1145a',
      },
      {
        firstname: 'Anson',
        lastname: 'Bowgen',
        avatar_url: 'https://robohash.org/dignissimossintid.png?size=50x50&set=set1',
        job: 'Account Coordinator',
        following: true,
        id: '4e38bd67-8dbe-45d9-96c0-94966e225e24',
      },
      {
        firstname: 'Cameron',
        lastname: 'McGeagh',
        avatar_url: 'https://robohash.org/nequeprovidentet.png?size=50x50&set=set1',
        job: 'Systems Administrator II',
        following: true,
        id: 'b019ed96-514b-4075-8b27-516debe8a1f5',
      },
      {
        firstname: 'Correna',
        lastname: 'Ormerod',
        avatar_url: 'https://robohash.org/laudantiuminventoreiure.png?size=50x50&set=set1',
        job: 'Structural Engineer',
        following: true,
        id: 'b64ddf00-659d-411e-8f07-eb87f3d730b8',
      },
      {
        firstname: 'Corabelle',
        lastname: 'Poser',
        avatar_url: 'https://robohash.org/inciduntrepellenduslabore.png?size=50x50&set=set1',
        job: 'Software Consultant',
        following: false,
        id: '974d4db5-222a-40ea-b2d3-2c71c17eed3e',
      },
      {
        firstname: 'Gertrudis',
        lastname: 'Rapinett',
        avatar_url: 'https://robohash.org/commodicumquetempore.png?size=50x50&set=set1',
        job: 'Research Assistant IV',
        following: false,
        id: 'b2783b42-33e4-4b0a-86d0-ae0cc8224264',
      },
      {
        firstname: 'Rosemarie',
        lastname: 'Bruna',
        avatar_url: 'https://robohash.org/consequunturodiominima.png?size=50x50&set=set1',
        job: 'Research Nurse',
        following: false,
        id: 'a3a99d73-4877-4aba-950f-f863d6f1fb12',
      },
      {
        firstname: 'Rozanne',
        lastname: 'Dossettor',
        avatar_url: 'https://robohash.org/aearatione.png?size=50x50&set=set1',
        job: 'VP Product Management',
        following: true,
        id: '11a3ed57-72ea-4960-916d-af876ca03cc6',
      },
    ],
  },
  {
    id: '6efb7a00-392b-4af5-96fc-dd78ec63378e',
    user: {
      firstname: 'Benedicto',
      lastname: 'Causnett',
      avatar_url: 'https://robohash.org/idquiamagni.png?size=50x50&set=set1',
      job: 'Human Resources Assistant II',
      following: false,
    },
    created_at: '3/12/2022',
    description:
      'Injury of right internal carotid artery, intracranial portion, not elsewhere classified with loss of consciousness greater than 24 hours with return to pre-existing conscious level, subsequent encounter',
    total_visits: 886,
    total_comments: 781,
    viewed_by: [
      {
        firstname: 'Marge',
        lastname: 'Ginnety',
        avatar_url: 'https://robohash.org/delectusimpeditut.png?size=50x50&set=set1',
        job: 'Analog Circuit Design manager',
        following: true,
        id: '0dc73b6c-8a1c-47d4-9ab9-50635b28c07e',
      },
      {
        firstname: 'Shay',
        lastname: 'Tree',
        avatar_url: 'https://robohash.org/temporibusquammolestias.png?size=50x50&set=set1',
        job: 'Senior Financial Analyst',
        following: true,
        id: 'b10337b2-49fa-44be-9d43-91bfe1864174',
      },
      {
        firstname: 'Willis',
        lastname: 'Rens',
        avatar_url: 'https://robohash.org/aliquamexpeditaeveniet.png?size=50x50&set=set1',
        job: 'Staff Scientist',
        following: false,
        id: '1a2986e1-932e-41a0-a081-5a2fa840da12',
      },
      {
        firstname: 'Niccolo',
        lastname: 'Pavelka',
        avatar_url: 'https://robohash.org/quasautsed.png?size=50x50&set=set1',
        job: 'Environmental Tech',
        following: false,
        id: 'b37b7a6a-5165-466e-8d4d-5115fe388fc3',
      },
      {
        firstname: 'Tessy',
        lastname: 'Macquire',
        avatar_url: 'https://robohash.org/consequunturbeataeminima.png?size=50x50&set=set1',
        job: 'Social Worker',
        following: false,
        id: 'a27d6378-e835-4b27-ac4b-41edd16daccd',
      },
      {
        firstname: 'Andee',
        lastname: 'Leahey',
        avatar_url: 'https://robohash.org/accusantiumametquasi.png?size=50x50&set=set1',
        job: 'Clinical Specialist',
        following: false,
        id: '5e86c1d9-a41e-48cf-a93b-43acf992a9ac',
      },
      {
        firstname: 'Janel',
        lastname: 'Stansfield',
        avatar_url: 'https://robohash.org/aspernaturnumquamet.png?size=50x50&set=set1',
        job: 'Internal Auditor',
        following: true,
        id: 'cf581ee9-5c1d-47f1-91a8-c485a6c5f199',
      },
    ],
  },
  {
    id: '367eeb15-6dae-44b3-9a67-60f1ad614bcc',
    user: {
      firstname: 'Pattin',
      lastname: 'Brassill',
      avatar_url: 'https://robohash.org/quisquamsuntarchitecto.png?size=50x50&set=set1',
      job: 'Recruiting Manager',
      following: false,
    },
    created_at: '10/31/2022',
    description: 'Placenta accreta, unspecified trimester',
    total_visits: 729,
    total_comments: 781,
    viewed_by: [
      {
        firstname: 'Jacqui',
        lastname: 'Gillebride',
        avatar_url: 'https://robohash.org/exercitationemnobisquidem.png?size=50x50&set=set1',
        job: 'Database Administrator I',
        following: false,
        id: 'e922a929-f874-4b69-98e5-1e5e541890b9',
      },
      {
        firstname: 'Justus',
        lastname: 'Semens',
        avatar_url: 'https://robohash.org/inquiavel.png?size=50x50&set=set1',
        job: 'Environmental Tech',
        following: true,
        id: 'c41e2570-df0a-4ce6-8852-4a61348aca2d',
      },
      {
        firstname: 'Frankie',
        lastname: 'Kach',
        avatar_url: 'https://robohash.org/animivoluptatessuscipit.png?size=50x50&set=set1',
        job: 'Quality Control Specialist',
        following: true,
        id: '66a54a27-9c65-4744-9fc8-28a2fc7b1d91',
      },
      {
        firstname: 'Estell',
        lastname: 'Meneghi',
        avatar_url: 'https://robohash.org/laudantiuminventoresed.png?size=50x50&set=set1',
        job: 'Design Engineer',
        following: true,
        id: 'f4d3b21a-205b-4bb3-8a7c-c86070233e5a',
      },
      {
        firstname: 'Ara',
        lastname: 'Ciottoi',
        avatar_url: 'https://robohash.org/abiustoanimi.png?size=50x50&set=set1',
        job: 'Senior Quality Engineer',
        following: false,
        id: '2fda86f0-696d-40c6-885a-c805e08843c4',
      },
      {
        firstname: 'Denice',
        lastname: 'Gofford',
        avatar_url: 'https://robohash.org/facereveritatiscommodi.png?size=50x50&set=set1',
        job: 'Nurse Practicioner',
        following: false,
        id: '5cc72930-bd8d-4e07-9eac-05027b615369',
      },
      {
        firstname: 'Kendre',
        lastname: 'Ricketts',
        avatar_url: 'https://robohash.org/voluptatemdoloressed.png?size=50x50&set=set1',
        job: 'Safety Technician IV',
        following: false,
        id: 'dea9f08a-fce4-4cb2-b01b-6203bf237580',
      },
      {
        firstname: 'Pietro',
        lastname: 'Scholefield',
        avatar_url: 'https://robohash.org/inprovidentquasi.png?size=50x50&set=set1',
        job: 'Quality Engineer',
        following: true,
        id: '54fd8c71-c178-4445-8051-774b13d56c5b',
      },
      {
        firstname: 'Waylon',
        lastname: 'Waudby',
        avatar_url: 'https://robohash.org/fugiteteius.png?size=50x50&set=set1',
        job: 'Electrical Engineer',
        following: true,
        id: '54e9eb47-b723-4b0a-acea-988887ab4e6a',
      },
      {
        firstname: 'Maris',
        lastname: 'Ewbanks',
        avatar_url: 'https://robohash.org/nonvitaequi.png?size=50x50&set=set1',
        job: 'Project Manager',
        following: true,
        id: '788c062d-eee7-462e-87ab-22b9e443b3dc',
      },
    ],
  },
  {
    id: 'df81192f-f990-4840-8d16-5a4cfcd5bf94',
    user: {
      firstname: 'Alexandra',
      lastname: 'Durn',
      avatar_url: 'https://robohash.org/nobisquosnon.png?size=50x50&set=set1',
      job: 'Electrical Engineer',
      following: false,
    },
    created_at: '10/11/2022',
    description: 'War operations involving thermal radiation effect of nuclear weapon',
    total_visits: 891,
    total_comments: 544,
    viewed_by: [
      {
        firstname: 'Margy',
        lastname: 'Manifold',
        avatar_url: 'https://robohash.org/etoccaecaticupiditate.png?size=50x50&set=set1',
        job: 'Assistant Professor',
        following: true,
        id: '39459ad6-7f1e-496c-8bc2-3bff28bdde7c',
      },
      {
        firstname: 'Gardy',
        lastname: 'Newlands',
        avatar_url: 'https://robohash.org/accusamusconsecteturitaque.png?size=50x50&set=set1',
        job: 'Engineer II',
        following: true,
        id: '98d7714c-4800-47c6-9edf-8699cecc3e30',
      },
      {
        firstname: 'Kristofer',
        lastname: 'Fritchly',
        avatar_url: 'https://robohash.org/velitautemenim.png?size=50x50&set=set1',
        job: 'Quality Engineer',
        following: false,
        id: 'caf5225a-9c92-4e98-b7f0-7e29c0f8f317',
      },
      {
        firstname: 'Damon',
        lastname: 'Osbidston',
        avatar_url: 'https://robohash.org/voluptasquocorrupti.png?size=50x50&set=set1',
        job: 'Senior Financial Analyst',
        following: true,
        id: 'c942c7aa-26cc-4f97-83ba-34c4951c3d93',
      },
      {
        firstname: 'Karmen',
        lastname: 'Kasparski',
        avatar_url: 'https://robohash.org/eaquenonratione.png?size=50x50&set=set1',
        job: 'Social Worker',
        following: false,
        id: '4cb14bfe-3a9d-4ecc-9695-2e32eab5cbdf',
      },
      {
        firstname: 'Darda',
        lastname: 'Pflieger',
        avatar_url: 'https://robohash.org/abitaquesed.png?size=50x50&set=set1',
        job: 'Electrical Engineer',
        following: true,
        id: '2214dae4-0560-4d76-ad92-6703d5c532c3',
      },
      {
        firstname: 'Larine',
        lastname: 'Dyzart',
        avatar_url: 'https://robohash.org/quiutenim.png?size=50x50&set=set1',
        job: 'Clinical Specialist',
        following: true,
        id: '83029ef8-6dd1-403a-97c0-59d887e3c07d',
      },
      {
        firstname: 'Cosetta',
        lastname: 'Grimsdyke',
        avatar_url: 'https://robohash.org/autemfugitillum.png?size=50x50&set=set1',
        job: 'Sales Associate',
        following: true,
        id: '6049d858-30e4-46d1-bab3-0de765e97520',
      },
      {
        firstname: 'Robb',
        lastname: 'Keggin',
        avatar_url: 'https://robohash.org/quasblanditiismaxime.png?size=50x50&set=set1',
        job: 'Junior Executive',
        following: false,
        id: 'f9f18162-49ff-4663-baaa-61e1bcde46d4',
      },
    ],
  },
  {
    id: '46201e8d-c1cf-410b-894b-4e6f43fe5ab2',
    user: {
      firstname: 'Jared',
      lastname: 'Forestall',
      avatar_url: 'https://robohash.org/omnisincidunttenetur.png?size=50x50&set=set1',
      job: 'Assistant Manager',
      following: true,
    },
    created_at: '4/24/2022',
    description: 'Fall from stairs and steps due to ice and snow',
    total_visits: 855,
    total_comments: 26,
    viewed_by: [],
  },
  {
    id: '830ac5de-e316-4aff-b866-b70c53049a47',
    user: {
      firstname: 'Letisha',
      lastname: 'Cheke',
      avatar_url: 'https://robohash.org/estenimnatus.png?size=50x50&set=set1',
      job: 'Senior Financial Analyst',
      following: false,
    },
    created_at: '2/19/2022',
    description:
      'Fracture of unspecified part of body of right mandible, subsequent encounter for fracture with routine healing',
    total_visits: 215,
    total_comments: 670,
    viewed_by: [
      {
        firstname: 'Robby',
        lastname: 'Andreasen',
        avatar_url: 'https://robohash.org/placeatconsequaturoccaecati.png?size=50x50&set=set1',
        job: 'Chief Design Engineer',
        following: true,
        id: '4f076e70-5643-41d2-ba8a-fd8a5e483476',
      },
    ],
  },
];
