export default [
  {
    id: '2686837a-6873-4f6a-8759-0ffe024bb076',
    user: {
      firstname: 'Sheelah',
      lastname: 'Doyley',
      avatar_url: 'https://robohash.org/natusquiadipisci.png?size=50x50&set=set1',
      job: 'Senior Quality Engineer',
      following: 16,
    },
    created_at: '10/23/2022',
    description: 'Assault by sharp glass, initial encounter',
    total_visits: 85,
    total_comments: 54,
    viewed_by: [
      {
        firstname: 'Emalee',
        lastname: 'Rawlyns',
        avatar_url: 'https://robohash.org/doloribusestdolore.png?size=50x50&set=set1',
        job: 'Unsp injury of anterior tibial artery, right leg, sequela',
        following: 43,
        id: 'f6e0be18-e627-43bc-b9fb-51f24875640e',
      },
      {
        firstname: 'Teodorico',
        lastname: 'McCluney',
        avatar_url: 'https://robohash.org/nisiquasitempora.png?size=50x50&set=set1',
        job: 'Legal intervnt w unsp explosv, law enforc offl injured, init',
        following: 69,
        id: 'cd2e8751-f3c9-4752-a5d9-df6dd6f83cc6',
      },
      {
        firstname: 'Alix',
        lastname: 'Lucchi',
        avatar_url: 'https://robohash.org/etodiodebitis.png?size=50x50&set=set1',
        job: 'Malignant neoplasm of undescended right testis',
        following: 90,
        id: 'd3c4cd47-794b-44de-9098-a1e641bb7401',
      },
      {
        firstname: 'Klaus',
        lastname: 'Blanche',
        avatar_url: 'https://robohash.org/velitaquesunt.png?size=50x50&set=set1',
        job: 'Other contact with shark',
        following: 46,
        id: 'd01657bd-b59e-4469-95f2-c4db91b9d167',
      },
      {
        firstname: 'Caz',
        lastname: 'Shimwell',
        avatar_url: 'https://robohash.org/temporesequiconsequatur.png?size=50x50&set=set1',
        job: 'Oth fracture of T9-T10 vertebra, subs for fx w routn heal',
        following: 63,
        id: '77b3daeb-7a06-4e30-b7ba-95defba43618',
      },
    ],
  },
  {
    id: '79692b95-0585-4dc4-9ee7-2080513755d9',
    user: {
      firstname: 'Rudy',
      lastname: 'Burgisi',
      avatar_url: 'https://robohash.org/magnamdelenitireiciendis.png?size=50x50&set=set1',
      job: 'Sales Associate',
      following: 99,
    },
    created_at: '3/13/2022',
    description: 'Other disorders of muscle tone of newborn',
    total_visits: 43,
    total_comments: 97,
    viewed_by: [
      {
        firstname: 'Alison',
        lastname: 'Wabe',
        avatar_url: 'https://robohash.org/adquomagni.png?size=50x50&set=set1',
        job: 'Exposure to other ionizing radiation',
        following: 65,
        id: 'e2c980c1-717c-44c5-8875-02ba58f3ecb9',
      },
      {
        firstname: 'Emelina',
        lastname: 'Jerosch',
        avatar_url: 'https://robohash.org/quidemasperioresnihil.png?size=50x50&set=set1',
        job: 'Terrorism involving nuclear weapons, terrorist injured, init',
        following: 17,
        id: 'f4f6a4ff-a238-454b-b39a-8991b34f1130',
      },
      {
        firstname: 'Theobald',
        lastname: 'Kirtland',
        avatar_url: 'https://robohash.org/facilisofficiain.png?size=50x50&set=set1',
        job: 'Other intervertebral disc displacement, thoracic region',
        following: 51,
        id: '2fe8a8e2-6dd9-4d09-9f9b-07e1cc011f98',
      },
    ],
  },
];
